spring.application.name=busTest

spring.datasource.url=jdbc:postgresql://localhost:5432/bus
spring.datasource.username=postgres
spring.datasource.password=1234

# ?? 15?
server.servlet.session.timeout=15m

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
# ???? validate?
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always

# kakao??
kakao.api.rest-key=b40bc447fcee597e69563415d7c44937
kakao.api.geocoding-url=https://dapi.kakao.com/v2/local/search/address.json
kakao.navi.directions-url=https://apis-navi.kakaomobility.com/v1/directions